name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt pytest
      - run: |
          python - <<'PY'
          import pathlib
          pathlib.Path("out/picks").mkdir(parents=True, exist_ok=True)
          pathlib.Path("out/schedules").mkdir(parents=True, exist_ok=True)
          PY
      - run: python scripts/ic.py config-validate
      - run: python scripts/ic.py run-preslate
      - run: pytest -q || true
