
name: ci
on:
  push: { branches: ["**"] }
  pull_request: { branches: ["**"] }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -U pip
          pip install -e .[dev]
      - name: Lint & Type
        run: |
          source .venv/bin/activate
          ruff check src
          mypy src
      - name: Tests
        run: |
          source .venv/bin/activate
          pytest -q
